### ISSUE TITLE
DateTimePicker add new bindable property

### ISSUE THREAD

**Issue by tobiaszuercher** [ghiscoding/Aurelia-Bootstrap-Plugins#14]
Hi,
you provide two options to bind: model & value.

```
  @bindable({defaultBindingMode: bindingMode.twoWay}) model;
  @bindable({defaultBindingMode: bindingMode.twoWay}) value;
```

Would you be happy to add another bindable property which holds the value in for example iso8601?

The problem is that I always have to convert the binded values before i can send it to my api, which is a annoying. It would make our life so much easier with another property, something like

```@bindable({defaultBindingMode: bindingMode.twoWay}) iso8601;``` where we can directly bind it.

My API sends dates in iso8601 as a string (e.g. 2017-05-23T00:00:00.0000000Z). it works for the first time binding. but if I re-assign the model with the new value from the API (for example because of a reset button), then i get: `Uncaught Error: Datetimepicker, model.bind must be of type Date`

It would really make everything much easier if we'd get a properly iso formatted property which can be used to bind it directly to a model which can be sent to an API. 

value: doesn't work, because it's formatted for the UI.
date: the date is in json a string --> `Uncaught Error: Datetimepicker, model.bind must be of type Date`

**Comment by tobiaszuercher** [comment]
Maybe another option is:

`abp-datetime-picker.js`:

`if (!Date.parse(newValue)) {` instead of `if (typeof newValue.getMonth !== 'function') {`

I'm just testing this out now.

**Comment by ghiscoding** [comment]
Your `Date.parse` seems to be an acceptable solution. Are you able to test it out? 

If you want to test it and don't know how, you can download the plugin project and run `gulp build` then take the `dist` folder and go under your project `node_modules`, search for `aurelia-bootstrap-datetimepicker` and replace the `dist` folder. 

As for adding a 3rd binding, I don't think that's a good thing to do. We should be able to do everything to the 2 provided.

**Comment by tobiaszuercher** [comment]
i'm testing it right know. 

i think we have two problems here. the `date.parse` solves one thing. (also relates to #13)

i still think a 3rd binding makes sense, otherwise we always have to patch the value before sending it to a backend. what is your concern about it?

btw: thank you a lot for your fast answer!

**Comment by ghiscoding** [comment]
I'll wait for your result on testing that. I'm working now and don't use `Aurelia` yet sadly. So I only pass time on this plugin on my free time. 

As for the 3rd binding, if I start adding a binding every time someone wants a different Date format/object/type/... that would be much more than 3 (today it's ISO, tomorrow who knows...). I already added a `Date` object binding because it was asked and for that one I agree because it makes sense. But adding binding to the plugin add performance degradation, the 2 bindings that I currently have are two-way binding which mean that changing the `model.bind` will call a `modelChanged()` but also calls a `valueChanged()` and vice versa (one call the other). Adding a 3rd two-way binding would add complexity and slower performance.

If someone wants a different Date format/object/type, that person can just add her own customized `valueConverter` without affecting performance for others.

**Comment by ghiscoding** [comment]
Looking at [MDN Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) docs, it seems that a check against `NaN` is more appropriate

> Return value
> A number representing the milliseconds elapsed since January 1, 1970, 00:00:00 UTC and the date obtained by parsing the given string representation of a date. If the argument doesn't represent a valid date, NaN is returned.

So if I take your code change suggestion
> `if (!Date.parse(newValue)) {` instead of `if (typeof newValue.getMonth !== 'function') {`

Should it be more like this instead?
`if (!isNaN(Date.parse(newValue))) {`

EDIT
Actually I should say `if (isNaN(Date.parse(newValue))) {`

**Comment by ghiscoding** [comment]
This should be fixed per your provided suggestions, so thanks a lot :)
Please update to latest [NPM version 1.0.8](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker)

If it's still an issue, please provide more details or open another issue. 

As for your other request, I still believe that you should use a `valueConverter` for your custom need.
Thanks
