### ISSUE TITLE
Value binding not initialized correctly

### ISSUE THREAD

**Issue by thejaff2** [ghiscoding/Aurelia-Bootstrap-Plugins#2]
Creating a separate issue for this.

value.bind is not initialized correctly (I have also tried model.bind). Setting a property in the viewmodel.activated() does not update the view (standard html-controls works in this way). Setting it in attached() works.

Another possibly related scenario: I am using a custom popover from "aurelia-bootstrap" (see [https://tochoromero.github.io/aurelia-bootstrap/#/popover](url)). Here also, the abp-datetime-picker does not pick up on changes from the viewmodel (the other way, from view to viewmodel, works though).

**Comment by ghiscoding** [comment]
Thanks, I will take that in consideration. I think that I finally got the other plugin that I'm working on (`Bootstrap-Selected`) working the way you want. That is, it binds the output from a change on the custom element (View), I can also pre-define value from the constructor (ViewModel) and at last I can finally change value from a button click (View) with a function that does a value change of the custom element in the (ViewModel).

I'm planning to have the same functionalities in current plugin, did I cover everything or did I miss a test, functionality? I think the biggest challenge might be to have the binding work from View to ViewModel for both binding (the formatted date & the Date object), we'll see how it goes. 

Feel free to add comments, I will be looking into the refactoring soon. 

_Note, thanks for the patience has this is all done in my free time_

**Comment by ghiscoding** [comment]
Closing since I just released a major version [1.0.0 on NPM](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker). Make sure to rewrite your options call by the new `options.bind` for example `options.bind="{ format: 'YYYY-MM-DD' }"`. Give it a try and see if it's all good... Also both `value.bind` and `model.bind` are `two-way` binding so any of the 2 will/can affect the picker.

There's a lot of changes, like new Global Options, so take a look at the [README](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker). 

I will update the Clients (CLI/Webpack) tomorrow
