### ISSUE TITLE
multiple selection mode not always working

### ISSUE THREAD

**Issue by amayr666** [ghiscoding/Aurelia-Bootstrap-Plugins#22]
Hi, 
setting the `multiple="true"` attribute doesn't always work since the check in `abp-select.js` on line 77 `this.multiple = this.util.parseBool(this.multiple || this.elm.getAttribute('multiple'));` requires the form `multiple="true"`, but just `multiple `is also valid html. This breaks some browsers/Servers.

regards

**Comment by ghiscoding** [comment]
Pull Request are welcome if you want to fix it.

**Comment by ghiscoding** [comment]
Alright it's all done, please note that I have decided to increase the version to `1.0.0` [(as shown on NPM)](https://www.npmjs.com/package/aurelia-bootstrap-select) to make it officially release and align with the other plugins which were already as `1.x`. 
By the way, since I was at it, I also made the change on the `disabled` attribute.

Thanks for the feedback and PR, if you like the plugin, you could also upvote :)
