### ISSUE TITLE
Bootstrap 4 dropped support for input-group-addon

### ISSUE THREAD

**Issue by jereckley** [ghiscoding/Aurelia-Bootstrap-Plugins#36]
So this can be fixed by specifying bootstrap@4.0.0-beta.2 but still something that needs to be addressed: Bootstrap 4 is dropping support for input-group-addon so 4.0.0-beta.3 breaks the date picker. 

[New format](https://getbootstrap.com/docs/4.0/components/input-group/) requires bootstrap input-group-prepend and input-group-append with a nested `<span class="input-group-text">icon here</span>`.

**Comment by ghiscoding** [comment]
would it be possible to make a PR that would work with both versions?

**Comment by ghiscoding** [comment]
Fixed in latest version [NPM 1.1.0](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker), new Global Options were added to deal with this, so make sure to change the `bootstrapVersion = 4` in your Global Options. You can see some references in the [Global Options](https://github.com/ghiscoding/Aurelia-Bootstrap-Plugins/tree/master/aurelia-bootstrap-datetimepicker#global-options) readme. I also added another global option to change the Bootstrap 4 button class, I used `btn-outline-secondary` by default, again look at the Global Options to know more about that.

**Comment by jereckley** [comment]
Awesome turn around! Thanks

**Comment by ghiscoding** [comment]
Oops, I forgot to remove the bootstrapVersion flag that I added to the View while testing it. Pushed another version on [NPM 1.1.1](https://www.npmjs.com/package/aurelia-bootstrap-datetimepicker)

Here's what it looks line in the final
![2018-01-06_18-28-18](https://user-images.githubusercontent.com/643976/34644946-64413afc-f30f-11e7-8b7a-92bb64131d40.gif)
