### ISSUE TITLE
Support 'required' validation attribute for abp-select

### ISSUE THREAD

**Issue by Mobe91** [ghiscoding/Aurelia-Bootstrap-Plugins#59]
For single and multiple select `abp-select` it would be nice to specify whether user input is required by adding support for a `required` attribute.

**Comment by ghiscoding** [comment]
I added `bindable` for both `readonly` and `required`, I didn't test it so please give that a try with latest version `1.3.2`

**Comment by ghiscoding** [comment]
I had forgot to push the new version `1.3.2` at the time but it's available now and I tried it, the `required` shows up. However the `readonly` is not a valid property of a `select`, so I'll remove that one in future version.

Closing since it seems to be working. 
Please reply if there's any other problems, thanks
