### ISSUE TITLE
typeahead

### ISSUE THREAD

**Issue by johntom** [ghiscoding/Aurelia-Bootstrap-Plugins#65]
I see you plan on adding typeahead and think that pagination ("infinite scrolling") for remote data sources would be a great addition.
John

**Comment by ghiscoding** [comment]
I had plan to add Typeahead but that was quite some time ago and my focus switched to another project. I should probably remove the "coming soon" since I don't think it will in the short term anyway. This is the Open Source, it's free and comes from people like me who devote some time to libraries like this one. If you want to help, then PR are more than welcome, I'm afraid that I can't do much more than that
